### PR TITLE
Improve docs with interactive tutorial

### PR DESCRIPTION
**Pull request by maticaputti**
**What this PR does / why we need it**: 
Hey guys! I spent some time working on an "interactive" version of the [Chartify tutorial notebook](https://github.com/spotify/chartify/blob/master/examples/Chartify%20Tutorial.ipynb). We've created [RMOTR Notebooks](https://notebooks.rmotr.com/) for our students, to help them get started.

With this version, anybody can just start working on the tutorial immediately in just a couple of seconds.

**Special notes for your reviewer**: 
I'm also working on the [Chartify examples notebook](https://notebooks.rmotr.com/spotify/interactive-chartify-examples-bedf977d), I'll update it as soon as it's done.

Any feedback is greatly appreciated!

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maticaputti** [comment]
Hey Chris! Thanks 😁 . The notebooks will not update automatically yet, but I can keep it in sync as `examples/Chartify Tutorial.ipynb` is updated. Also, I can email you the credentials to log in into the account and see/change whatever you see fit.

PS: Examples on `examples/Examples.ipynb` are almost done 💪

**Comment by maticaputti** [comment]
Hey Chris! I understand. Our Notebooks are free, and users don't even need to create an account. They can try everything anonymously. We've created this product as a support for students and people learning, so we're committed to make it extremely simple for them.

And about updating. You're right, it'd be better to update it automatically, but again, I can keep it updated for the time being until we have some webhook version that can update automatically.

**Comment by santiagobasulto** [comment]
I'll chime in if I'm allowed 😁. @cphalpert thanks very much for your feedback. This is **really** useful for us, made us realize we have to work a little bit more to improve our "image". Our service is completely free, and there's a fully anonymous view where a user can interact with the Jupyter without registration required; compared to colab, which requires an account to run notebooks.

@cphalpert what would you need, based on your experience, to incorporate some of what @maticaputti has done? The ability to automatically update the docs, and anything else?

**Comment by cphalpert** [comment]
Appreciate the effort. I brought this up to others on the team and we all agreed that we'd prefer to support open source solutions for now.

**Comment by maticaputti** [comment]
Thanks very much Chris. I'll close this PR then. I'll keep these tutorials for my students. If you guys change your mind just let me know, we're also trying to support the OSS community including Jupyter and Python.

**Pull request closed without merging**
