### PR TITLE
Bump Pandas requirement to 1.0.0

### PR DESCRIPTION
**Pull request by tomasaschan**
**What this PR does / why we need it**:

Pandas 1.0 has been out for a few months, and seems stable enough that we should start supporting it!

In addition, I noticed some inconsistencies between versions used in the package requirements itself,
and in the requirements specified for local development. These have now been rectified (and future-proofed)
by including the package `requirements.txt` from the dev one instead of specifying everything twice.

**Special notes for your reviewer**:

On my local setup (Windows with WSL) there are some problems with chromedriver that I haven't been
able to figure out. Because of this, saving images as png doesn't work, and thus that test has been
skipped when I've tested locally. I doubt that it would make a difference for this change, but might
be worth double-checking in the PR builds.

**Release note**:

```release-note
Bump Pandas requirement to 1.0
```

### CODE REVIEW

**Comment by tomasaschan** [comment]
py3.5 fails because it can't find `pandas>=1.0.0<2`, which makes sense - Pandas 1.0 [requires Python 3.6.1 or higher](https://pandas.pydata.org/docs/whatsnew/v1.0.0.html#increased-minimum-version-for-python). What is the policy for supporting 3.5 here? Would it make sense to bump Chartify's minimum python version to 3.6 too (and make the corresponding `tox` config updates)?

py3.6 fails with the following `TypeError`:
```
pd.MultiIndex(
                levels=[['a', 'b'], ['1', '2', '3']],
                labels=[[0, 0, 0, 1, 1], [1, 0, 2, 0, 1]],
>               names=['category1', 'category2'])
E           TypeError: __new__() got an unexpected keyword argument 'labels'
```
Assume this is something that has changed in the Pandas API and I can change the code accordingly. However, that won't help if Chartify must keep supporting 3.5.

Is it OK to drop 3.5 support?

**Comment by cphalpert** [comment]
Sure, I'm open to bumping the python version minimum to be in line with the newest pandas requirements. Thanks for your help with this!

**Comment by tomasaschan** [comment]
Cool! I'll update this PR with those changes tomorrow.

Which Python versions should I add to the tox test specs? All the way up to 3.9?

**Comment by cphalpert** [comment]
Yeah that works

**Comment by tomasaschan** [comment]
The build error on 3.8 seems to be related to some recently introduced thing in Pyflakes, and we're getting a pretty old version for some reason. Investigating...

**Comment by cphalpert** [comment]
Thanks Tomas! Building off of your work here #108

**Pull request closed without merging**
